# Generated by Django 5.1.15 on 2026-08-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('artist_name', models.CharField(max_length=255)),
                ('album_name', models.CharField(blank=True, default='', max_length=255)),
                ('cover_url', models.URLField(blank=True, default='', max_length=500)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('audio_url', models.URLField(blank=True, default='', max_length=500)),
                ('genre', models.CharField(blank=True, default='', max_length=100)),
                ('license_ccurl', models.URLField(blank=True, default='', max_length=500)),
                ('cached_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-cached_at'],
            },
        ),
    ]
