# Generated by Django 5.1.15 on 2026-08-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
