# Generated by Django 5.1.15 on 2026-08-03 21:00

import connect.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('playlists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_code', models.CharField(db_index=True, default=connect.models.generate_invite_code, max_length=10, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('ended', 'Ended')], default='waiting', max_length=15)),
                ('current_jamendo_track_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_connect_sessions', to=settings.AUTH_USER_MODEL)),
                ('playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connect_sessions', to='playlists.playlist')),
            ],
        ),
        migrations.CreateModel(
            name='ConnectParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connect_participations', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='connect.connectsession')),
            ],
            options={
                'unique_together': {('session', 'user')},
            },
        ),
    ]
