import requests
import logging

logger = logging.getLogger(__name__)

class PipedClient:
    """
    Client for Piped API (YouTube Music alternative).
    Fetches tracks, streams, and lyrics.
    """
    BASE_URL = "https://pipedapi.kavin.rocks"

    def _get(self, endpoint, params=None):
        if params is None:
            params = {}

        url = f"{self.BASE_URL}/{endpoint.lstrip('/')}"
        try:
            response = requests.get(url, params=params, timeout=15)
            response.raise_for_status()
            return response.json()
        except requests.RequestException as e:
            logger.error(f"HTTP request error querying Piped endpoint {endpoint}: {e}")
            return None

    def search_tracks(self, query=None, limit=20, offset=0, genre=None):
        """Search tracks. Piped doesn't use offset natively, but we can simulate by slicing."""
        search_query = query if query else (genre if genre else "top hits")
        
        # Piped filter for music songs
        params = {
            'q': search_query,
            'filter': 'music_songs'
        }
        
        data = self._get('/search', params)
        if not data or 'items' not in data:
            return []

        items = data['items']
        # Apply pseudo-pagination
        paginated_items = items[offset:offset+limit]
        
        return [self._format_track(t) for t in paginated_items]

    def get_trending_tracks(self, limit=20, offset=0):
        """Fetch trending / popular tracks by searching for a generic popular term."""
        return self.search_tracks(query="top music hits 2024", limit=limit, offset=offset)

    def get_track_detail(self, video_id):
        """Fetch a single track details by ID, including audio stream URL."""
        data = self._get(f'/streams/{video_id}')
        if not data:
            return None
            
        return self._format_stream_detail(data, video_id)

    def get_lyrics(self, video_id):
        """Extract subtitles/lyrics from stream data if available."""
        data = self._get(f'/streams/{video_id}')
        if not data or 'subtitles' not in data:
            return None
            
        subs = data.get('subtitles', [])
        for sub in subs:
            # Try to get auto-generated or manual lyrics
            if sub.get('autoGenerated', False) or sub.get('mimeType') == 'text/vtt':
                return sub.get('url')
        
        # Return first available subtitle if any
        if len(subs) > 0:
            return subs[0].get('url')
            
        return None

    def get_genres(self):
        """Fetch preset default genres list."""
        return [
            {"id": "pop", "name": "Pop"},
            {"id": "hip hop", "name": "Hip-Hop"},
            {"id": "rnb", "name": "R&B"},
            {"id": "rock", "name": "Rock"},
            {"id": "electronic", "name": "Électronique"},
            {"id": "jazz", "name": "Jazz"},
            {"id": "classical", "name": "Classique"},
            {"id": "latin", "name": "Latino"},
            {"id": "afrobeats", "name": "Afrobeats"},
            {"id": "kpop", "name": "K-Pop"},
        ]

    def _format_track(self, raw_item):
        """Standardize raw Piped search item into clean normalized representation."""
        # Piped duration is in seconds
        duration = raw_item.get('duration', 0)
        
        return {
            "youtube_id": raw_item.get('url', '').replace('/watch?v=', ''),
            "title": raw_item.get('title', 'Titre inconnu'),
            "artist_name": raw_item.get('uploaderName', 'Artiste inconnu'),
            "album_name": "Single", # Search results rarely have album names
            "cover_url": raw_item.get('thumbnail', ''),
            "duration_seconds": duration,
            "audio_url": "", # Will be fetched dynamically when playing
            "genre": "Pop", 
            "license_ccurl": 'https://youtube.com',
        }
        
    def _format_stream_detail(self, stream_data, video_id):
        """Standardize stream detail response."""
        # Extract best audio stream (m4a or webm)
        audio_streams = stream_data.get('audioStreams', [])
        best_audio = ""
        if audio_streams:
            # Prefer mp4/m4a for better compatibility on mobile devices
            mp4_streams = [s for s in audio_streams if 'mp4' in s.get('mimeType', '')]
            if mp4_streams:
                best_audio = mp4_streams[0].get('url', '')
            else:
                best_audio = audio_streams[0].get('url', '')
                
        return {
            "youtube_id": video_id,
            "title": stream_data.get('title', 'Titre inconnu'),
            "artist_name": stream_data.get('uploader', 'Artiste inconnu'),
            "album_name": "Single",
            "cover_url": stream_data.get('thumbnailUrl', ''),
            "duration_seconds": stream_data.get('duration', 0),
            "audio_url": best_audio,
            "genre": "",
            "license_ccurl": 'https://youtube.com',
        }
